### PR TITLE
Change status code when archive not writable, fix up response headers

### LINKED ISSUE #2: Change status code for unwriteable hyperdrives
Consider changing the status code from 500 to 405 Method not Allowed (or 403 Unauthorized). 405 also returns which methods _are_ allowed.

### PR DESCRIPTION
**Pull request by RangerMauve**
Closes #2 

@DeltaF1 how does this look?

You get a 403 if you try to write somewhere that isn't writable.
You get the list of allowed methods when you try a method that isn't allowed.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -217,10 +218,12 @@ module.exports = function makeFetch (opts = {}) {
           return new FakeResponse(statusCode, 'ok', responseHeaders, stream, url)
         }
       } else {
+        responseHeaders.set('Allow', 'GET, HEAD, PUT, DELETE')
         return new FakeResponse(405, 'Method Not Allowed', responseHeaders, intoStream('Method Not Allowed'), url)
       }
     } catch (e) {
-      return new FakeResponse(500, 'server error', responseHeaders, intoStream(e.stack), url)
+      const status = (e.message === NOT_WRITABLE_ERROR) ? 403 : 500
```
Comment (DeltaF1) [inline index.js:225]: If it's a 403 then it should return some text like "Hyperdrive not writeable" instead of the stacktrace

File: index.js [hunk 2]
```diff
@@ -222,8 +222,10 @@ module.exports = function makeFetch (opts = {}) {
         return new FakeResponse(405, 'Method Not Allowed', responseHeaders, intoStream('Method Not Allowed'), url)
       }
     } catch (e) {
-      const status = (e.message === NOT_WRITABLE_ERROR) ? 403 : 500
-      return new FakeResponse(status, 'server error', responseHeaders, intoStream(e.stack), url)
+      const isUnauthorized = (e.message === NOT_WRITABLE_ERROR)
+      const status = isUnauthorized ? 403 : 500
+      const message = isUnauthorized ? 'not authorized' : 'server error'
```
Comment (DeltaF1) [inline index.js:227]: Very nitpicky, but could those be capitalized? Otherwise looks good
